// generated by Fast Light User Interface Designer (fluid) version 1.0309

#ifndef layout_h
#define layout_h

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Input.H>
#include "../include/callback.h"
#include <FL/Fl_Choice.H>
#include <FL/Fl_Output.H>

class Layout : public Fl_Window {
public:
    Layout(int w, int h, const char* title);
    ~Layout();
    
private:
    Fl_Input* input1;
    Fl_Choice* choice1;
    Fl_Input_Choice* input_choice1;
    
    void setup_widgets();  // Função para configurar widgets
};

extern Fl_Double_Window *tela_principal;

extern Fl_Group *menu;
extern Fl_Button *btn_menu_venda;
extern Fl_Button *btn_menu_cadastro;
extern Fl_Button *btn_menu_estoque;
extern Fl_Button *btn_menu_financeiro;


extern Fl_Group *menu_venda;
extern Fl_Input_Choice *buscar_nome_prod;
extern Fl_Input_Choice *buscar_nome_prod;
extern Fl_Input_Choice *buscar_nome_prod;
extern Fl_Output *prc_prod;
extern Fl_Input *desconto_venda;
extern Fl_Button *btn_nova_venda;
extern Fl_Button *btn_canc_venda;
extern Fl_Button *btn_visu_venda;

extern Fl_Group *menu_nova_venda;
extern Fl_Return_Button *btn_confir_venda;
extern Fl_Input *in_produto_venda;

extern Fl_Group *menu_canc_venda;
extern Fl_Input_Choice *buscar_prod;
extern Fl_Return_Button *btn_confir_canc;

extern Fl_Group *menu_ver_venda;

//extern  *busca_lista_venda;


extern Fl_Group *menu_estoque;
extern Fl_Choice *cad_prod_estoque;
extern Fl_Button *edt_prod_estoque;
extern Fl_Button *exc_prod_estoque;

extern Fl_Return_Button *btn_voltar;


extern Fl_Group *menu_cad_prod;

extern Fl_Input *in_nome_prod;
extern Fl_Input_Choice *in_marca_prod;
extern Fl_Input_Choice *in_categoria_prod;
extern Fl_Input_Choice *in_caracteristica_prod;
extern Fl_Input_Choice *in_tamanho_prod;
extern Fl_Input_Choice *in_fornecedor_prod;
extern Fl_Input *in_prc_compra_prod;
extern Fl_Input *in_prc_venda_prod;
extern Fl_Input *in_descricao_prod;
extern Fl_Input *in_obs_prod;
extern Fl_Button *btn_confir_cadastro;

extern Fl_Group *menu_seleção;
extern Fl_Choice *seletor_cadastro;

extern Fl_Group *menu_cad_marca;
extern Fl_Input *in_nome_marca;
extern Fl_Input_Choice *in_fornecedor_marca;

extern Fl_Group *menu_cad_fornecedor;
extern Fl_Input *in_nome_fornecedor; 
extern Fl_Input *in_telefone_fornecedor;

Fl_Double_Window* main_window();
#endif
