// generated by Fast Light User Interface Designer (fluid) version 1.0309

#ifndef layout_h
#define layout_h

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Input.H>
#include "../include/callback.h"

extern Fl_Double_Window *tela_principal;

extern Fl_Group *menu;
extern Fl_Button *btn_menu_venda;
extern Fl_Button *btn_menu_estoque;

//extern void tela_venda(Fl_Button*, void*);
extern Fl_Group *menu_venda;
extern Fl_Button *btn_nova_venda;
extern Fl_Button *btn_canc_venda;
extern Fl_Button *btn_visu_vendas;

extern Fl_Group *tela_menu_estoque;
extern Fl_Button *cad_prod_estoque;
extern Fl_Button *edt_prod_estoque;
extern Fl_Button *exc_prod_estoque;

extern Fl_Return_Button *btn_voltar;


extern Fl_Group *menu_cad_prod;

extern Fl_Input *in_nome_prod;
extern Fl_Input_Choice *in_marca_prod;
extern Fl_Input_Choice *in_categoria_prod;
extern Fl_Input_Choice *in_caracteristica_prod;
extern Fl_Input_Choice *in_tamanho_prod;
extern Fl_Input_Choice *in_fornecedor_prod;
extern Fl_Input *in_prc_compra_prod;
extern Fl_Input *in_prc_venda_prod;
extern Fl_Input *in_descricao_prod;
extern Fl_Input *in_obs_prod;
extern Fl_Button *btn_confir_cadastro;

Fl_Double_Window* main_window();
#endif
