// generated by Fast Light User Interface Designer (fluid) version 1.0309

#include "layout.h"

Fl_Double_Window* main_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1364, 739, "MENU");
    w = o; if (w) {/* empty */}
    o->box(FL_THIN_UP_BOX);
    { new Fl_Button(1050, 130, 230, 35, "VENDAS");
    } // Fl_Button* o
    { new Fl_Button(1050, 225, 230, 35, "ESTOQUE");
    } // Fl_Button* o
    o->size_range(1364, 739, 1364, 739);
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Double_Window* estoque_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1364, 739, "ESTOQUE");
    w = o; if (w) {/* empty */}
    { new Fl_Return_Button(1195, 50, 110, 25, "Voltar");
    } // Fl_Return_Button* o
    { new Fl_Button(1030, 165, 230, 35, "Cadastar Produto");
    } // Fl_Button* o
    { new Fl_Button(1030, 295, 230, 35, "Excluir Produto");
    } // Fl_Button* o
    { new Fl_Button(1030, 230, 230, 35, "Editar Produto");
    } // Fl_Button* o
    o->size_range(1364, 739, 1364, 739);
    o->end();
  } // Fl_Double_Window* o
  return w;
}
