// generated by Fast Light User Interface Designer (fluid) version 1.0309

#ifndef layout_h
#define layout_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
Fl_Double_Window* main_window();
#endif
